import pytest
from typing import Iterator

from advent.advent_of_code_2024.day08.main import (
    exercise_one
)

@pytest.fixture
def example_data() -> Iterator[str]:
    data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

    return iter(data.splitlines())

def test_exercise_one():
    assert exercise_one() == 14